const express = require('express')
const router = express.Router()
const { myPosts, createPost, allPosts} = require('../controller/posts')
const { tradeBooks, acceptTrade, declineTrade, rateBooks, toRate} = require('../controller/trade')

router.route('/books').get(myPosts).post(createPost)
router.get('/allposts', allPosts)
router.route('/:wantsId/trade/:offersId').get(tradeBooks)
router.get('/trade/:id/accept', acceptTrade)
router.get('/trade/:id/decline', declineTrade)
router.post('/rating/:bookId', rateBooks)
router.get('/ratebooks',toRate)
